import {
  HardDrive,
  Database,
  Zap,
  MessageSquare,
  Bell,
  Shield,
  Server,
  Container,
  Mail,
  Clock,
  FileText,
  Activity,
  Globe,
  Key,
  Layers,
  Workflow,
  DatabaseZap,
  MemoryStick,
  Cloud,
  Lock,
  CloudCog,
  Search,
  type LucideIcon,
} from "lucide-react"

const SERVICE_ICON_MAP: Record<string, LucideIcon> = {
  s3: HardDrive,
  dynamodb: Database,
  lambda: Zap,
  sqs: MessageSquare,
  sns: Bell,
  iam: Shield,
  ec2: Server,
  ecs: Container,
  ses: Mail,
  events: Clock,
  "events-scheduler": Clock,
  logs: FileText,
  kinesis: Activity,
  route53: Globe,
  kms: Key,
  cloudformation: Layers,
  states: Workflow,
  stepfunctions: Workflow,
  rds: DatabaseZap,
  elasticache: MemoryStick,
  cloudwatch: Cloud,
  secretsmanager: Lock,
  ssm: CloudCog,
  sts: Shield,
  acm: Lock,
  elbv2: Globe,
  appsync: Search,
  cognito: Shield,
  "cognito-idp": Shield,
}

export function getServiceIcon(service: string): LucideIcon {
  return SERVICE_ICON_MAP[service.toLowerCase()] ?? Server
}
